mixed-port: 7890
external-controller: 127.0.0.1:9090
mode: rule # rule / global / direct / script (default is rule)
log-level: debug # silent / error / warning / info / debug
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
interface-name: "ä»¥å¤ªç½‘" # interface name at Windows control panel
dns:
  enable: true
  listen: 0.0.0.0:5301
  ipv6: false # when the false, response to AAAA questions will be empty
  use-hosts: true # lookup hosts and return IP record
  enhanced-mode: redir-host # or fake-ip

  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114 # 114DNS
    - 119.29.29.29 # DNSPod Public DNS+
    - 223.5.5.5 # Ali DNS
    - 1.1.1.1 # Cloudflare DNS
    - 8.8.8.8 # GoogleDNS
    - 9.9.9.9 # IBM Quad9 DNS
    - 80.80.80.80 # Freenom World
    - 208.67.222.222 # Cisco OpenDNS
    - 101.101.101.101 # TWNIC Quad101 DNS

  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR

  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"

  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  nameserver:
    - 114.114.114.114 # 114DNS
    - 119.29.29.29 # DNSPod Public DNS+
    - 223.5.5.5 # Ali DNS
    - tls://dns.rubyfish.cn:853 # Rubyfish DNS
    - tls://dns.alidns.com:853 # Ali DNS
    - tls://doh.pub:853 # DNSPod Public DNS+
    - tls://dns.pub:853 # DNSPod Public DNS+
    - https://doh.pub/dns-query # DNSPod Public DNS+
    - https://dns.pub/dns-query # DNSPod Public DNS+
    - https://223.5.5.5/dns-query # Ali DNS
    - https://dns.alidns.com/dns-query # Ali DNS
    - https://rubyfish.cn/dns-query # Rubyfish DNS
    - https://dns.rubyfish.cn/dns-query # Rubyfish DNS
  fallback:
    - tls://1.1.1.1:853 # Cloudflare DNS
    - tls://8.8.8.8:853 # GoogleDNS
    - tls://public.dns.iij.jp:853 # IIJ Public DNS
    - tls://101.101.101.101:853 # TWNIC Quad101 DNS
    - https://dns.google/dns-query # GoogleDNS
    - https://public.dns.iij.jp/dns-query # IIJ Public DNS
    - https://dns.twnic.tw/dns-query # TWNIC Quad101 DNS
    - https://doh.opendns.com/dns-query # Cisco OpenDNS
    - https://1.1.1.1/dns-query # Cloudflare DNS
    - https://dns.cloudflare.com/dns-query # Cloudflare DNS
    - https://9.9.9.9/dns-query # IBM Quad9 DNS
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.github.com"
  # Lookup domains via specific nameservers
  # nameserver-policy:
  #   'www.baidu.com': '114.114.114.114'
  #   '+.internal.crop.com': '10.0.0.1'
proxy-groups:
  - name: ğŸ”° èŠ‚ç‚¹é€‰æ‹©
    type: select
    use:
      - è®¢é˜…é“¾æ¥1
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - è®¢é˜…é“¾æ¥1
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    use:
      - è®¢é˜…é“¾æ¥1
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸŒ å›½å†…åª’ä½“
    type: select
    use:
      - è®¢é˜…é“¾æ¥1
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    use:
      - è®¢é˜…é“¾æ¥1
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
    type: select
    use:
      - è®¢é˜…é“¾æ¥1
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    use:
      - è®¢é˜…é“¾æ¥1
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    use:
      - è®¢é˜…é“¾æ¥1
    proxies:
      - ğŸ”° èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©

rule-providers:
  å¹¿å‘ŠåŸŸååˆ—è¡¨:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/å¹¿å‘ŠåŸŸååˆ—è¡¨.yaml
    interval: 86400

  iCloudåŸŸååˆ—è¡¨:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/iCloudåŸŸååˆ—è¡¨.yaml
    interval: 86400

  Appleç›´è¿:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/Appleç›´è¿.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  ä»£ç†åŸŸååˆ—è¡¨:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/ä»£ç†åŸŸååˆ—è¡¨.yaml
    interval: 86400

  ç›´è¿åŸŸååˆ—è¡¨:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/ç›´è¿åŸŸååˆ—è¡¨.yaml
    interval: 86400

  ä¸“ç”¨åŸŸååˆ—è¡¨:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/ä¸“ç”¨åŸŸååˆ—è¡¨.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.tx\
      t"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.t\
      xt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr\
      .txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications\
      .txt"
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
  - RULE-SET,ç›´è¿åŸŸååˆ—è¡¨,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,applications,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ä¸“ç”¨åŸŸååˆ—è¡¨,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,lancidr,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,cncidr,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ä»£ç†åŸŸååˆ—è¡¨,ğŸ”° èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,telegramcidr,ğŸ“² ç”µæŠ¥ä¿¡æ¯
  - RULE-SET,iCloudåŸŸååˆ—è¡¨,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Appleç›´è¿,ğŸ è‹¹æœæœåŠ¡
  # - RULE-SET,google,DIRECT
  - RULE-SET,å¹¿å‘ŠåŸŸååˆ—è¡¨,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
